# Generated by Django 4.2.11 on 2025-03-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_icon', models.CharField(max_length=50)),
                ('blog_title', models.CharField(max_length=50)),
                ('blog_des', models.TextField()),
            ],
        ),
    ]
